name = "CertifiedMonodromyComputation"
uuid = "340e340e-340e-340e-340e-340e340e340e"
authors = ["Kisun Lee"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[compat]
AbstractAlgebra = "0.47.6"
GAP = "0.16.2"
LinearAlgebra = "1.11.0"
MultivariatePolynomials = "0.5.13"
Nemo = "0.53.1"
